### ISSUE TITLE
Repeated warnings 'Failed to notify spy' when using with another core extension declared in .mvn folder

### ISSUE THREAD

**Issue by jibidus** [jcgay/maven-profiler#199]
When I use maven-profiler with another core extension where:

* `maven-profiler` is installed in `$M2_HOME/lib/ext` folder 
* the other extension is declared in `.mvn/` folder

.. I got the following line many times each time a use a `maven` command :
```
[WARNING] Failed to notify spy fr.jcgay.maven.profiler.ProfilerEventSpy: null
```

Here is the stack trace when adding `-X` parameter:

```
java.lang.NullPointerException
        at fr.jcgay.maven.profiler.ProfilerEventSpy.onEvent(ProfilerEventSpy.java:81)
        at org.apache.maven.eventspy.internal.EventSpyDispatcher.onEvent(EventSpyDispatcher.java:104)
        at org.apache.maven.eventspy.internal.EventSpyRepositoryListener.artifactResolved(EventSpyRepositoryListener.java:88)
        [...]
```

The exception is raised [here](https://github.com/jcgay/maven-profiler/blob/master/src/main/java/fr/jcgay/maven/profiler/ProfilerEventSpy.java#L81), in `ProfilerEventSpy` where `onEvent()` is called before `init()`.
Do someone know if it is an issue with `maven-profiler`, or with `maven`? And how how to solve this issue?
I can create a pull request if necessary.

I created a dedicated project for the demonstrate: https://github.com/jibidus/maven-profiler-bug-demo

**Comment by hazendaz** [comment]
Having same issue.

**Comment by jcgay** [comment]
Thank you for the very detailed report 👍
